plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-spaceship

markdown: kramdown
kramdown: 
  math_engine: mathjax
  parse_block_html: true  # Ensure MathJax scripts inside HTML work
mathjax: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      usemathjax: true
  - scope:
      path: ""
    values:
      layout: "default"
